### PR TITLE
Version 4.10.0

### PR DESCRIPTION
**Pull request by uerceg**
- Added support for iOS 10.
- Added revenue deduplication for Android platform.
- Added an option for enabling/disabling tracking while app is in background.
- Added a callback to be triggered if event is successfully tracked.
- Added a callback callback to be triggered if event tracking failed.
- Added a callback to be triggered if session is successfully tracked.
- Added a callback to be triggered if session tracking failed.
- Added possibility to set session callback and partner parameters with `addSessionCallbackParameter` and `addSessionPartnerParameter` methods.
- Added possibility to remove session callback and partner parameters by key with `removeSessionCallbackParameter` and `removeSessionPartnerParameter` methods.
- Added possibility to remove all session callback and partner parameters with `resetSessionCallbackParameters and `resetSessionPartnerParameters` methods.
- Added new Suppress log level.
- Added possibility to delay initialisation of the SDK while maybe waiting to obtain some session callback or partner parameters with delayed start feature on adjust config instance.
- Added callback method to get deferred deep link content into the app.
- Added possibility to decide whether the SDK should launch the deferred deep link or not.
- Added possibility to set user agent manually on adjust config instance.
- Deferred deep link info will now arrive as part of the attribution response and not as part of the answer to first session.
- Updated docs.
- Native SDKs stability updates and improvements.
- Updated native iOS SDK to version 4.10.2.
- Updated native Android SDK to version 4.10.2.

### CODE REVIEW

**Comment by uerceg** [comment]
@adjust/integration

**Comment by luckey01** [comment]
I can see a few 'readme' like files.
https://github.com/adjust/cocos2dx_sdk/pull/11/files#diff-cb31d76c654226bd31c7b43bddf99642R1

https://github.com/adjust/cocos2dx_sdk/pull/11/files#diff-3429146cff49cb402517f67279801f57R1

and

https://github.com/adjust/cocos2dx_sdk/pull/11/files#diff-875166290e7bd53ae37cf994e5953379R1

all three need a going over?

**Comment by luckey01** [comment]
ios.md and android.md yes. windows.md no.

**Comment by uerceg** [comment]
Replaced with https://github.com/adjust/cocos2dx_sdk/pull/14.

**Pull request closed without merging**
